spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=create-drop

app.jwt.secret=YjY5YjAyN2JhMzA5ZWI2Y2RlZjgxYjZhOGEwOTU5YTM4MmY1ZDBmYjU3ZTM1ZDRlMDRiY2FkMGQ3MDcwZmI5YjJmYjY1YjAyN2JhMzA5ZWI2Y2RlZjgxYjZhOGEwOTU5YTM4MmY1ZDBmYjU3ZTM1ZDRlMDRiY2FkMGQ3MDcwZmI5YjI=

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.root=INFO
logging.level.com.example.employeeapi=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n

management.endpoints.web.exposure.include=health,info,metrics
